import type { Equipment, Operations, Projects } from "@sever/contracts";
import { one, query, type Sql } from "../../core/db.js";
import { BadRequest, NotFound } from "../../core/errors.js";
type Row={id:string;number:string;kind:Operations.OperationDocumentKind;status:Operations.OperationDocumentStatus;payload:Operations.OperationPayload;document_at:Date;version:number;created_by:string;created_at:Date;updated_by:string;updated_at:Date;posted_at:Date|null;reversed_at:Date|null};
type RevisionRow={id:string;document_id:string;version:number;action:Operations.OperationRevisionAction;payload:Operations.OperationPayload;document_at:Date;actor_id:string;created_at:Date};
const dto=(r:Row):Operations.OperationDocumentDTO=>({id:r.id,number:r.number,kind:r.kind,status:r.status,payload:r.payload,documentAt:r.document_at.toISOString(),version:r.version,createdBy:r.created_by,createdAt:r.created_at.toISOString(),updatedBy:r.updated_by,updatedAt:r.updated_at.toISOString(),postedAt:r.posted_at?.toISOString()??null,reversedAt:r.reversed_at?.toISOString()??null});
const revisionDto=(r:RevisionRow):Operations.OperationRevisionDTO=>({id:r.id,documentId:r.document_id,version:r.version,action:r.action,payload:r.payload,documentAt:r.document_at.toISOString(),actorId:r.actor_id,createdAt:r.created_at.toISOString()});
export function createOperationsService(db:Sql,equipment:Equipment.EquipmentService,projects:Projects.ProjectsService):Operations.OperationsService{
 const load=async(id:string)=>one<Row>(db,`SELECT * FROM operations.documents WHERE id=$1`,[id]);
 const enrich=async(payload:Operations.OperationPayload)=>{let enriched=payload;if(payload.kind==="transfer"){const unit=await equipment.getUnit(payload.unitId);if(!unit)throw NotFound("unit",payload.unitId);enriched={...payload,fromWarehouseId:unit.warehouseId};}if(payload.kind==="inventory"){enriched={...payload,lines:await Promise.all(payload.lines.map(async line=>{const unit=await equipment.getUnit(line.unitId);if(!unit)throw NotFound("unit",line.unitId);return{...line,beforeStatus:unit.status};}))};}return enriched;};
 const revision=(documentId:string,version:number,action:Operations.OperationRevisionAction,payload:Operations.OperationPayload,documentAt:Date,actorId:string)=>query(db,`INSERT INTO operations.document_revisions(document_id,version,action,payload,document_at,actor_id) VALUES($1,$2,$3,$4,$5,$6)`,[documentId,version,action,JSON.stringify(payload),documentAt,actorId]);
 const accountingPayload=(payload:Operations.OperationPayload)=>{const {note:_,...accounting}=payload;return accounting;};
 const preservePostedEnrichment=(payload:Operations.OperationPayload,current:Operations.OperationPayload):Operations.OperationPayload=>{if(payload.kind==="transfer"&&current.kind==="transfer")return{...payload,fromWarehouseId:current.fromWarehouseId};if(payload.kind==="inventory"&&current.kind==="inventory"){const before=new Map(current.lines.map(line=>[line.unitId,line.beforeStatus]));return{...payload,lines:payload.lines.map(line=>({...line,beforeStatus:before.get(line.unitId)}))};}return payload;};
 const dateValue=(value?:string)=>{const date=value?new Date(value):new Date();if(Number.isNaN(date.getTime()))throw BadRequest("некорректная дата документа");return date;};
 const apply=async(payload:Operations.OperationPayload,actorId:string,reverse=false)=>{
  if(payload.kind==="issue") { if(!reverse && (await projects.getProject(payload.projectId))?.operationStage !== "pickup") throw BadRequest("выдача доступна только на этапе «Забор»");let result:unknown=null;if(payload.unitIds.length)result=reverse?await equipment.returnUnits({projectId:payload.projectId,returnedUnitIds:payload.unitIds,expectedUnitIds:payload.unitIds,actorId,note:"Сторно документа"}):await equipment.issueUnits({projectId:payload.projectId,unitIds:payload.unitIds,actorId,note:payload.note??undefined});for(const line of payload.quantityLines??[]){if(reverse)await equipment.returnQuantity({projectId:payload.projectId,modelId:line.modelId,warehouseId:line.warehouseId??undefined,qty:line.qty,actorId,note:"Сторно документа"});else await equipment.issueQuantity({projectId:payload.projectId,modelId:line.modelId,warehouseId:line.warehouseId??undefined,qty:line.qty,actorId,note:payload.note??undefined});}return result; }
  if(payload.kind==="return") {let result:unknown=null;if(reverse?payload.returnedUnitIds.length:payload.expectedUnitIds.length)result=reverse?await equipment.issueUnits({projectId:payload.projectId,unitIds:payload.returnedUnitIds,actorId,note:"Сторно документа"}):await equipment.returnUnits({projectId:payload.projectId,returnedUnitIds:payload.returnedUnitIds,expectedUnitIds:payload.expectedUnitIds,warehouseId:payload.warehouseId,actorId,note:payload.note??undefined});for(const line of payload.quantityLines??[]){if(reverse)await equipment.issueQuantity({projectId:payload.projectId,modelId:line.modelId,warehouseId:line.warehouseId??undefined,qty:line.qty,actorId,note:"Сторно документа"});else await equipment.returnQuantity({projectId:payload.projectId,modelId:line.modelId,warehouseId:line.warehouseId??undefined,qty:line.qty,actorId,note:payload.note??undefined});}return result;}
  if(payload.kind==="transfer"){const target=reverse?payload.fromWarehouseId:payload.warehouseId;if(!target)throw BadRequest("source warehouse is required for reversal");return equipment.transferUnit(payload.unitId,target,actorId,reverse?"Сторно документа":payload.note??null);}
  for(const line of payload.lines){if(reverse){if(line.beforeStatus)await equipment.changeStatus(line.unitId,line.beforeStatus,actorId,"Сторно инвентаризации");}else if(!line.present)await equipment.changeStatus(line.unitId,"lost",actorId,payload.note??"Не найдено при инвентаризации");}
 };
 return {
  async list(){return(await query<Row>(db,`SELECT * FROM operations.documents ORDER BY document_at DESC,created_at DESC LIMIT 500`)).map(dto);},
  async get(id){const r=await load(id);return r?dto(r):null;},
  async history(id){return(await query<RevisionRow>(db,`SELECT * FROM operations.document_revisions WHERE document_id=$1 ORDER BY created_at DESC`,[id])).map(revisionDto);},
  async create(payload,actorId,documentAt){const enriched=await enrich(payload);const at=dateValue(documentAt);const prefix={issue:"ISS",return:"RET",transfer:"TRN",inventory:"INV"}[payload.kind];const number=`${prefix}-${at.toISOString().slice(0,10).replaceAll("-","")}-${Math.random().toString(36).slice(2,6).toUpperCase()}`;const r=await one<Row>(db,`INSERT INTO operations.documents(number,kind,payload,document_at,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$5) RETURNING *`,[number,payload.kind,JSON.stringify(enriched),at,actorId]);await revision(r!.id,r!.version,"created",enriched,r!.document_at,actorId);return dto(r!);},
  async update(id,payload,actorId,documentAt){const current=await load(id);if(!current)throw NotFound("operation document",id);if(current.status==="reversed")throw BadRequest("сторнированный документ нельзя редактировать");const enriched=current.status==="draft"?await enrich(payload):preservePostedEnrichment(payload,current.payload);if(current.status==="posted"&&JSON.stringify(accountingPayload(enriched))!==JSON.stringify(accountingPayload(current.payload)))throw BadRequest("в проведённом документе можно изменить только дату и комментарий");const at=documentAt?dateValue(documentAt):current.document_at;const updated=await one<Row>(db,`UPDATE operations.documents SET kind=$2,payload=$3,document_at=$4,version=version+1,updated_by=$5,updated_at=now() WHERE id=$1 AND status IN ('draft','posted') RETURNING *`,[id,payload.kind,JSON.stringify(enriched),at,actorId]);await revision(id,updated!.version,"edited",enriched,updated!.document_at,actorId);return dto(updated!);},
  async post(id,actorId){const r=await load(id);if(!r)throw NotFound("operation document",id);if(r.status!=="draft")throw BadRequest("only draft documents can be posted");await apply(r.payload,actorId);const updated=await one<Row>(db,`UPDATE operations.documents SET status='posted',posted_at=now(),version=version+1,updated_by=$2,updated_at=now() WHERE id=$1 AND status='draft' RETURNING *`,[id,actorId]);await revision(id,updated!.version,"posted",updated!.payload,updated!.document_at,actorId);return dto(updated!);},
  async reverse(id,actorId){const r=await load(id);if(!r)throw NotFound("operation document",id);if(r.status!=="posted")throw BadRequest("only posted documents can be reversed");await apply(r.payload,actorId,true);const updated=await one<Row>(db,`UPDATE operations.documents SET status='reversed',reversed_at=now(),version=version+1,updated_by=$2,updated_at=now() WHERE id=$1 AND status='posted' RETURNING *`,[id,actorId]);await revision(id,updated!.version,"reversed",updated!.payload,updated!.document_at,actorId);return dto(updated!);}
 };
}
